---
- name: Create Folder with Date
  hosts: all
  tasks:
    - name: Run Powershell command to create folder with date
      raw: New-Item -ItemType Directory -Path ".\$((Get-Date).ToString('yyyy-MM-dd'))"
