---
- name: Create Folder with Date
  hosts: all
  tasks:
    - name: Run Powershell command to create folder with date
      raw: powershell New-Item -ItemType Directory -Path "C:\$((Get-Date).ToString('yyyy-MM-dd'))"
